services:
  - type: web
    name: herdoza-fitness-gym
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.jsenvVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
