servi    buildCommand: npm install && cd backend && npm install && cd ../IPT-TAILWIND && npm install && cd .. && npm run buildes:
  - type: web
    name: herdoza-fitness-gym
    env: node
    rootDirectory: .
    buildCommand:npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
