services:
  - type: web
    name: herdoza-fitness-gym
    env: node
    rootDirectory: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_URL
        value: "https://herdoza-fitness-gym.onrender.com/admin"
      - key: FRONTEND_URL
        value: "https://herdoza-fitness-gym.onrender.com"
